print("Creating myGps folder")
fs.makeDir("myGps")
shell.run("cd myGps")
print("Downloading myGps.lua")
shell.run("https://raw.githubusercontent.com/K3vinb5/myGps/main/main/myGps.lua")
print("Downloading setup.lua")
shell.run("https://raw.githubusercontent.com/K3vinb5/myGps/main/main/setup.lua")
shell.run("cd ..")